[project]
name = "poetry-semvar-git-dependency"
version = "0.1.0"
description = "A Poetry plugin to enable semvar syntax for git dependency"
authors = [
    {name = "Satoshi",email = "6world4trigger@gmail.com"}
]
readme = "README.md"
requires-python = "3.10"
dependencies = [
    "poetry (>=2.0.1,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
